version: 2.1

executors:
  ubuntu_executor:
    machine:
      image: ubuntu-2004:202111-02

jobs:
  "test":
    executor: ubuntu_executor
    steps:
      - checkout
      - run:
          name: Run tests
          command:
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build:
    jobs:
      - test